uploads = []
generated = []

[[outputs]]
id = "DNYPbFPAJjS-si0mrrbw9"
uri = "file://CUPGS_All_Credentials.xlsx"
type = "table"
title = "CUPGS All Role Credentials"

[[outputs]]
id = "ycUOxBz4X2IOsPDwFD8Ju"
uri = "file://CUPGS_Credentials.xlsx"
type = "table"
title = "CUPGS_Credentials.xlsx — All Login Credentials"

[[outputs]]
id = "OA7nVdbZKzkulRJ6IOiT5"
uri = "file://exports/CUPGS-SE-Diagrams.pdf"
type = "pdf"
title = "CUPGS SE Diagrams — Redesigned Professional Layout (4 Pages)"

[[outputs]]
id = "y0EiIzTG1zDvJAXLgHeyg"
uri = "file://exports/plantuml/CUPGS-PlantUML-Diagrams.tar.gz"
type = "unspecified"
title = "CUPGS PlantUML Diagrams — All 4 Files (.tar.gz archive)"
