// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/diagrams/AllDiagramsPdf.tsx": () => import("../components/mockups/diagrams/AllDiagramsPdf.tsx"),
  "./components/mockups/diagrams/DfdLevel0.tsx": () => import("../components/mockups/diagrams/DfdLevel0.tsx"),
  "./components/mockups/diagrams/DfdLevel1.tsx": () => import("../components/mockups/diagrams/DfdLevel1.tsx"),
  "./components/mockups/diagrams/DfdLevel2.tsx": () => import("../components/mockups/diagrams/DfdLevel2.tsx"),
  "./components/mockups/diagrams/ErDiagram.tsx": () => import("../components/mockups/diagrams/ErDiagram.tsx")
};
