import { useState } from "react";
import { useRole } from "@/contexts/RoleContext";
import { useLocation } from "wouter";
import { useListDepartments } from "@workspace/api-client-react";
import { getApiUrl } from "@/lib/api";
import { getCupgsLogoDataUrl } from "@/lib/pdfLogo";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import {
  Download, FileText, Building2, BarChart3, Shield,
  Loader2, CheckCircle, AlertCircle, ChevronRight
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

const BPUT_BLUE = [13, 71, 115] as [number, number, number];
const BPUT_DARK = [8, 47, 80] as [number, number, number];
const BPUT_ACCENT = [0, 150, 136] as [number, number, number];

function fmt(v: number | null) {
  return v != null ? v.toFixed(2) : "N/A";
}

function ratingColor(v: number | null): [number, number, number] {
  if (v == null) return [150, 150, 150];
  if (v >= 4) return [0, 128, 0];
  if (v >= 3) return [200, 140, 0];
  return [200, 0, 0];
}

function drawCoverPage(doc: jsPDF, title: string, subtitle: string, generatedAt: string, logoUrl?: string | null) {
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();

  doc.setFillColor(...BPUT_DARK);
  doc.rect(0, 0, pw, 80, "F");

  doc.setFillColor(...BPUT_BLUE);
  doc.rect(0, 70, pw, 15, "F");

  if (logoUrl) {
    try {
      doc.addImage(logoUrl, "PNG", 12, 6, 18, 18);
    } catch {}
  }

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("CENTRE FOR UG & PG STUDIES (CUPGS), BPUT", pw / 2, 18, { align: "center" });
  doc.text("Chhend Colony, Rourkela, Odisha – 769015", pw / 2, 24, { align: "center" });

  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text(title, pw / 2, 44, { align: "center" });

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(subtitle, pw / 2, 54, { align: "center" });

  doc.setFontSize(9);
  doc.text("Academic Year: 2024-25 | Even Semester End Feedback", pw / 2, 64, { align: "center" });

  doc.setFillColor(230, 240, 255);
  doc.roundedRect(25, 95, pw - 50, 28, 3, 3, "F");
  doc.setTextColor(13, 71, 115);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("Generated by: CUPGS Academic Feedback Management System", pw / 2, 106, { align: "center" });
  doc.setFont("helvetica", "normal");
  doc.text(`Report Date: ${new Date(generatedAt).toLocaleString("en-IN", { day: "2-digit", month: "long", year: "numeric", hour: "2-digit", minute: "2-digit" })}`, pw / 2, 114, { align: "center" });
  doc.text("Classification: Confidential — For Internal Use Only", pw / 2, 122, { align: "center" });

  doc.setFillColor(245, 247, 250);
  doc.rect(0, 145, pw, ph - 145, "F");

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(50, 50, 50);
  doc.text("TABLE OF CONTENTS", 25, 162);
  doc.setDrawColor(...BPUT_BLUE);
  doc.setLineWidth(0.5);
  doc.line(25, 165, pw - 25, 165);

  const tocItems = [
    "Executive Summary ...........................................................................................................",
    "Department-wise Performance Comparison .....................................................................",
    "Rating Parameter Analysis (All Parameters) ...................................................................",
    "Top Performing Faculty .....................................................................................................",
    "Department-wise Detailed Breakdowns ............................................................................",
    "Student Feedback Comments ............................................................................................",
  ];
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const pageNums = ["2", "3", "3", "4", "4–6", "7"];
  tocItems.forEach((item, i) => {
    doc.setTextColor(60, 60, 60);
    doc.text(item, 30, 176 + i * 10);
    doc.setTextColor(...BPUT_BLUE);
    doc.text(pageNums[i], pw - 30, 176 + i * 10, { align: "right" });
  });

  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Page 1", pw / 2, ph - 8, { align: "center" });
}

function addPageHeader(doc: jsPDF, subtitle: string) {
  const pw = doc.internal.pageSize.getWidth();
  doc.setFillColor(...BPUT_BLUE);
  doc.rect(0, 0, pw, 22, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.text("CUPGS Academic Feedback Report", 15, 10);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text(subtitle, 15, 17);
  doc.setTextColor(0, 0, 0);
}

function addPageFooter(doc: jsPDF, pageNum: number, totalPages?: number) {
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(15, ph - 14, pw - 15, ph - 14);
  doc.setFontSize(7);
  doc.setTextColor(150, 150, 150);
  doc.text("CUPGS Feedback Management System — Confidential", 15, ph - 8);
  doc.text(totalPages ? `Page ${pageNum} of ${totalPages}` : `Page ${pageNum}`, pw - 15, ph - 8, { align: "right" });
}

function drawSectionTitle(doc: jsPDF, text: string, y: number): number {
  const pw = doc.internal.pageSize.getWidth();
  doc.setFillColor(230, 240, 252);
  doc.rect(12, y - 5, pw - 24, 10, "F");
  doc.setDrawColor(...BPUT_BLUE);
  doc.setLineWidth(1);
  doc.line(12, y - 5, 12, y + 5);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...BPUT_BLUE);
  doc.text(text, 18, y + 1.5);
  doc.setTextColor(0, 0, 0);
  doc.setLineWidth(0.3);
  return y + 12;
}

function drawStatBoxes(doc: jsPDF, stats: { label: string; value: string; sub?: string }[], y: number): number {
  const pw = doc.internal.pageSize.getWidth();
  const margin = 15;
  const gap = 4;
  const boxW = (pw - margin * 2 - gap * (stats.length - 1)) / stats.length;

  stats.forEach((s, i) => {
    const x = margin + i * (boxW + gap);
    doc.setFillColor(245, 250, 255);
    doc.setDrawColor(180, 210, 240);
    doc.setLineWidth(0.4);
    doc.roundedRect(x, y, boxW, 22, 2, 2, "FD");
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...BPUT_BLUE);
    doc.text(s.value, x + boxW / 2, y + 11, { align: "center" });
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(80, 80, 80);
    doc.text(s.label, x + boxW / 2, y + 17, { align: "center" });
    if (s.sub) {
      doc.setFontSize(6.5);
      doc.setTextColor(130, 130, 130);
      doc.text(s.sub, x + boxW / 2, y + 21, { align: "center" });
    }
  });

  doc.setTextColor(0, 0, 0);
  return y + 28;
}

function drawHorizontalBar(doc: jsPDF, label: string, value: number | null, x: number, y: number, barWidth: number) {
  const color = ratingColor(value);
  const pct = value != null ? (value / 5) : 0;
  const filledW = barWidth * pct;

  doc.setFontSize(8.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(60, 60, 60);
  doc.text(label, x, y);

  doc.setFillColor(225, 225, 225);
  doc.roundedRect(x + 68, y - 3.5, barWidth, 5, 1.5, 1.5, "F");

  if (filledW > 0) {
    doc.setFillColor(...color);
    doc.roundedRect(x + 68, y - 3.5, filledW, 5, 1.5, 1.5, "F");
  }

  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...color);
  doc.text(fmt(value) + " / 5", x + 68 + barWidth + 4, y);
  doc.setTextColor(0, 0, 0);
}

function drawDeptBarChart(doc: jsPDF, depts: { code: string; avgOverall: number | null }[], x: number, y: number, chartW: number, chartH: number) {
  const pw = doc.internal.pageSize.getWidth();
  const barCount = depts.length;
  const maxVal = 5;
  const barW = (chartW - 10) / barCount - 4;
  const scale = chartH / maxVal;

  doc.setDrawColor(210, 210, 210);
  doc.setLineWidth(0.3);
  for (let v = 0; v <= 5; v++) {
    const lineY = y + chartH - v * scale;
    doc.line(x, lineY, x + chartW, lineY);
    doc.setFontSize(6);
    doc.setTextColor(140, 140, 140);
    doc.text(v.toString(), x - 4, lineY + 1, { align: "right" });
  }

  depts.forEach((d, i) => {
    const barX = x + i * (barW + 4) + 5;
    const val = d.avgOverall ?? 0;
    const barH = val * scale;
    const barY = y + chartH - barH;

    const col = ratingColor(d.avgOverall);
    doc.setFillColor(...col);
    doc.rect(barX, barY, barW, barH, "F");

    doc.setFontSize(6.5);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...col);
    if (val > 0) doc.text(val.toFixed(1), barX + barW / 2, barY - 1.5, { align: "center" });
    doc.setFont("helvetica", "normal");
    doc.setTextColor(60, 60, 60);
    doc.text(d.code, barX + barW / 2, y + chartH + 5, { align: "center" });
  });
  doc.setTextColor(0, 0, 0);
}

interface FullReport {
  overall: {
    totalFeedback: number;
    totalDepartments: number;
    totalFaculty: number;
    totalCourses: number;
    avgOverall: number | null;
    avgCourseContent: number | null;
    avgTeachingQuality: number | null;
    avgLabFacilities: number | null;
    avgStudyMaterial: number | null;
  };
  departments: Array<{
    id: number; code: string; name: string; hodName: string | null;
    totalFaculty: number; totalCourses: number; totalFeedback: number;
    avgOverall: number | null; avgCourseContent: number | null;
    avgTeachingQuality: number | null; avgLabFacilities: number | null;
    avgStudyMaterial: number | null;
    facultyStats: Array<{
      id: number; name: string; designation: string; employeeId: string;
      feedbackCount: number; avgOverall: number | null;
      avgCourseContent: number | null; avgTeachingQuality: number | null;
      avgLabFacilities: number | null; avgStudyMaterial: number | null;
    }>;
  }>;
  topFaculty: Array<{
    id: number; name: string; designation: string;
    departmentCode: string; feedbackCount: number; avgOverall: number | null;
  }>;
  recentComments: Array<{
    comment: string | null; courseCode: string; deptCode: string; createdAt: string;
  }>;
  generatedAt: string;
}

async function generateOverallPDF(data: FullReport) {
  const logoUrl = await getCupgsLogoDataUrl();
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  const M = 15;
  const contentW = pw - M * 2;

  drawCoverPage(doc, "Institution Feedback Report", "Comprehensive Academic Feedback Analysis — All Departments", data.generatedAt, logoUrl);

  doc.addPage();
  addPageHeader(doc, "Executive Summary");
  let y = 30;

  y = drawSectionTitle(doc, "A. Institution-wide Summary", y);
  y = drawStatBoxes(doc, [
    { label: "Total Feedback", value: data.overall.totalFeedback.toString(), sub: "Responses" },
    { label: "Avg Overall Rating", value: fmt(data.overall.avgOverall), sub: "out of 5.00" },
    { label: "Departments", value: data.overall.totalDepartments.toString() },
    { label: "Total Faculty", value: data.overall.totalFaculty.toString() },
    { label: "Total Courses", value: data.overall.totalCourses.toString() },
  ], y);

  y = drawSectionTitle(doc, "B. Rating Parameter Breakdown", y + 2);
  const ratingParams: [string, number | null][] = [
    ["Course Content", data.overall.avgCourseContent],
    ["Teaching Quality", data.overall.avgTeachingQuality],
    ["Lab Facilities", data.overall.avgLabFacilities],
    ["Study Material", data.overall.avgStudyMaterial],
    ["Overall Satisfaction", data.overall.avgOverall],
  ];
  ratingParams.forEach(([label, val]) => {
    drawHorizontalBar(doc, label, val, M + 5, y, contentW - 100);
    y += 9;
  });

  y += 5;
  y = drawSectionTitle(doc, "C. Department Comparison Chart", y);
  const chartH = 45;
  drawDeptBarChart(doc, data.departments.map(d => ({ code: d.code, avgOverall: d.avgOverall })), M + 5, y, contentW - 10, chartH);
  y += chartH + 14;

  y = drawSectionTitle(doc, "D. Department Performance Table", y);
  autoTable(doc, {
    startY: y,
    margin: { left: M, right: M },
    head: [["Dept", "Department Name", "HOD", "Faculty", "Courses", "Responses", "Content", "Teaching", "Lab", "Material", "Overall"]],
    body: data.departments.map(d => [
      d.code,
      d.name,
      d.hodName ?? "—",
      d.totalFaculty.toString(),
      d.totalCourses.toString(),
      d.totalFeedback.toString(),
      fmt(d.avgCourseContent),
      fmt(d.avgTeachingQuality),
      fmt(d.avgLabFacilities),
      fmt(d.avgStudyMaterial),
      fmt(d.avgOverall),
    ]),
    headStyles: { fillColor: BPUT_BLUE, textColor: 255, fontStyle: "bold", fontSize: 7.5 },
    bodyStyles: { fontSize: 7.5 },
    alternateRowStyles: { fillColor: [245, 249, 255] },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 12 },
      1: { cellWidth: 35 },
      2: { cellWidth: 28 },
      6: { halign: "center" }, 7: { halign: "center" },
      8: { halign: "center" }, 9: { halign: "center" }, 10: { halign: "center" },
    },
    theme: "grid",
    didDrawCell: (hookData) => {
      if (hookData.section === "body" && hookData.column.index >= 6) {
        const val = parseFloat(hookData.cell.raw as string);
        if (!isNaN(val)) {
          const col = ratingColor(val);
          doc.setTextColor(col[0], col[1], col[2]);
        }
      }
    },
  });

  doc.addPage();
  addPageHeader(doc, "Top Performing Faculty & Department Details");
  y = 30;

  y = drawSectionTitle(doc, "E. Top 10 Performing Faculty (Institution-wide)", y);
  autoTable(doc, {
    startY: y,
    margin: { left: M, right: M },
    head: [["Rank", "Faculty Name", "Designation", "Department", "Responses", "Avg Rating"]],
    body: data.topFaculty.map((f, i) => [
      `#${i + 1}`,
      f.name,
      f.designation,
      f.departmentCode,
      f.feedbackCount.toString(),
      fmt(f.avgOverall),
    ]),
    headStyles: { fillColor: BPUT_BLUE, textColor: 255, fontStyle: "bold", fontSize: 8 },
    bodyStyles: { fontSize: 8.5 },
    alternateRowStyles: { fillColor: [245, 249, 255] },
    columnStyles: {
      0: { halign: "center", cellWidth: 14, fontStyle: "bold" },
      4: { halign: "center" },
      5: { halign: "center", fontStyle: "bold" },
    },
    theme: "grid",
    didDrawCell: (hookData) => {
      if (hookData.section === "body" && hookData.column.index === 5) {
        const val = parseFloat(hookData.cell.raw as string);
        if (!isNaN(val)) {
          const col = ratingColor(val);
          doc.setTextColor(col[0], col[1], col[2]);
        }
      }
    },
  });

  y = (doc as any).lastAutoTable.finalY + 10;
  y = drawSectionTitle(doc, "F. Department-wise Faculty Breakdown", y);

  for (const dept of data.departments) {
    if (y > ph - 60) { doc.addPage(); addPageHeader(doc, "Department Faculty Details"); y = 30; }

    doc.setFillColor(240, 245, 255);
    doc.roundedRect(M, y, contentW, 10, 2, 2, "F");
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...BPUT_BLUE);
    doc.text(`${dept.code} — ${dept.name}`, M + 4, y + 7);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(80, 80, 80);
    doc.text(`HOD: ${dept.hodName ?? "—"} | Faculty: ${dept.totalFaculty} | Feedback: ${dept.totalFeedback}`, pw - M - 4, y + 7, { align: "right" });
    doc.setTextColor(0, 0, 0);
    y += 13;

    if (dept.facultyStats.length > 0) {
      autoTable(doc, {
        startY: y,
        margin: { left: M + 3, right: M },
        head: [["Faculty Name", "Designation", "Responses", "Content", "Teaching", "Lab", "Material", "Overall"]],
        body: dept.facultyStats.map(f => [
          f.name, f.designation,
          f.feedbackCount.toString(),
          fmt(f.avgCourseContent), fmt(f.avgTeachingQuality),
          fmt(f.avgLabFacilities), fmt(f.avgStudyMaterial), fmt(f.avgOverall),
        ]),
        headStyles: { fillColor: [40, 80, 130], textColor: 255, fontSize: 7 },
        bodyStyles: { fontSize: 7.5 },
        alternateRowStyles: { fillColor: [248, 250, 255] },
        columnStyles: {
          2: { halign: "center" }, 3: { halign: "center" }, 4: { halign: "center" },
          5: { halign: "center" }, 6: { halign: "center" }, 7: { halign: "center", fontStyle: "bold" },
        },
        theme: "grid",
        didDrawCell: (hookData) => {
          if (hookData.section === "body" && hookData.column.index >= 3) {
            const val = parseFloat(hookData.cell.raw as string);
            if (!isNaN(val)) {
              const col = ratingColor(val);
              doc.setTextColor(col[0], col[1], col[2]);
            }
          }
        },
      });
      y = (doc as any).lastAutoTable.finalY + 8;
    } else {
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text("No faculty feedback data available.", M + 6, y + 4);
      y += 10;
    }
  }

  if (data.recentComments.length > 0) {
    if (y > ph - 60) { doc.addPage(); addPageHeader(doc, "Student Comments"); y = 30; }
    y = drawSectionTitle(doc, "G. Recent Student Comments", y);
    autoTable(doc, {
      startY: y,
      margin: { left: M, right: M },
      head: [["Course", "Dept", "Comment", "Date"]],
      body: data.recentComments.map(c => [
        c.courseCode, c.deptCode,
        c.comment ?? "—",
        new Date(c.createdAt).toLocaleDateString("en-IN"),
      ]),
      headStyles: { fillColor: BPUT_BLUE, textColor: 255, fontSize: 8 },
      bodyStyles: { fontSize: 7.5 },
      columnStyles: { 2: { cellWidth: 110 } },
      alternateRowStyles: { fillColor: [245, 249, 255] },
      theme: "grid",
    });
  }

  const pageCount = (doc.internal as any).getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    addPageFooter(doc, i, pageCount);
  }

  doc.save(`CUPGS_Institution_Feedback_Report_${new Date().toISOString().slice(0, 10)}.pdf`);
}

interface HodReportData {
  department: { id: number; name: string; code: string; hodName: string };
  summary: {
    totalFeedback: number; totalCourses: number; totalFaculty: number;
    avgOverall: number | null; avgCourseContent: number | null;
    avgTeachingQuality: number | null; avgLabFacilities: number | null; avgStudyMaterial: number | null;
  };
  facultyStats: Array<{
    id: number; name: string; designation: string; employeeId: string;
    courseCount: number; courseNames: string; feedbackCount: number;
    avgOverall: number | null; avgCourseContent: number | null;
    avgTeachingQuality: number | null; avgLabFacilities: number | null; avgStudyMaterial: number | null;
  }>;
  courseStats: Array<{
    id: number; code: string; name: string; semester: number; academicYear: string;
    facultyName: string; feedbackCount: number;
    avgOverall: number | null; avgCourseContent: number | null;
    avgTeachingQuality: number | null; avgLabFacilities: number | null; avgStudyMaterial: number | null;
  }>;
  recentComments: Array<{ comment: string | null; courseCode: string; section: string | null; createdAt: string }>;
  generatedAt: string;
}

async function generateDeptPDF(data: HodReportData, isAdmin = true) {
  const logoUrl = await getCupgsLogoDataUrl();
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  const M = 15;
  const contentW = pw - M * 2;
  const { department, summary, facultyStats, courseStats, recentComments, generatedAt } = data;

  drawCoverPage(
    doc,
    `${department.code} — Department Report`,
    department.name,
    generatedAt,
    logoUrl
  );

  doc.addPage();
  addPageHeader(doc, `${department.code} | ${department.name}`);
  let y = 30;

  doc.setFillColor(240, 245, 255);
  doc.roundedRect(M, y, contentW, 16, 2, 2, "F");
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(40, 40, 120);
  doc.text("HOD:", M + 5, y + 6);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(60, 60, 60);
  doc.text(department.hodName ?? "—", M + 18, y + 6);
  doc.setFont("helvetica", "bold");
  doc.text("Report Type:", M + 5, y + 12);
  doc.setFont("helvetica", "normal");
  doc.text(isAdmin ? "Admin Report — All Access" : "HOD Department Report", M + 32, y + 12);
  doc.setTextColor(0, 0, 0);
  y += 22;

  y = drawSectionTitle(doc, "A. Department Summary", y);
  y = drawStatBoxes(doc, [
    { label: "Feedback Responses", value: summary.totalFeedback.toString() },
    { label: "Avg Overall Rating", value: fmt(summary.avgOverall), sub: "out of 5.00" },
    { label: "Total Courses", value: summary.totalCourses.toString() },
    { label: "Total Faculty", value: summary.totalFaculty.toString() },
  ], y);

  y = drawSectionTitle(doc, "B. Rating Breakdown", y + 2);
  const ratingParams: [string, number | null][] = [
    ["Course Content", summary.avgCourseContent],
    ["Teaching Quality", summary.avgTeachingQuality],
    ["Lab Facilities", summary.avgLabFacilities],
    ["Study Material", summary.avgStudyMaterial],
    ["Overall Satisfaction", summary.avgOverall],
  ];
  ratingParams.forEach(([label, val]) => {
    drawHorizontalBar(doc, label, val, M + 5, y, contentW - 100);
    y += 9;
  });

  y += 4;
  y = drawSectionTitle(doc, "C. Faculty Performance Summary", y);
  autoTable(doc, {
    startY: y,
    margin: { left: M, right: M },
    head: [["Faculty Name", "Designation", "Employee ID", "Courses", "Responses", "Content", "Teaching", "Lab", "Material", "Overall"]],
    body: facultyStats.map(f => [
      f.name, f.designation, f.employeeId ?? "—",
      f.courseCount.toString(), f.feedbackCount.toString(),
      fmt(f.avgCourseContent), fmt(f.avgTeachingQuality),
      fmt(f.avgLabFacilities), fmt(f.avgStudyMaterial), fmt(f.avgOverall),
    ]),
    headStyles: { fillColor: BPUT_BLUE, textColor: 255, fontStyle: "bold", fontSize: 7.5 },
    bodyStyles: { fontSize: 7.5 },
    alternateRowStyles: { fillColor: [245, 249, 255] },
    columnStyles: {
      5: { halign: "center" }, 6: { halign: "center" },
      7: { halign: "center" }, 8: { halign: "center" },
      9: { halign: "center", fontStyle: "bold" },
    },
    theme: "grid",
    didDrawCell: (hookData) => {
      if (hookData.section === "body" && hookData.column.index >= 5) {
        const val = parseFloat(hookData.cell.raw as string);
        if (!isNaN(val)) { const col = ratingColor(val); doc.setTextColor(col[0], col[1], col[2]); }
      }
    },
  });

  y = (doc as any).lastAutoTable.finalY + 10;
  if (y > ph - 60) { doc.addPage(); addPageHeader(doc, `${department.code} | Course Report`); y = 30; }
  y = drawSectionTitle(doc, "D. Course-wise Feedback Report", y);

  autoTable(doc, {
    startY: y,
    margin: { left: M, right: M },
    head: [["Code", "Course Name", "Sem", "Faculty", "Responses", "Content", "Teaching", "Lab", "Material", "Overall"]],
    body: courseStats.map(c => [
      c.code, c.name, `${c.semester}`, c.facultyName,
      c.feedbackCount.toString(),
      fmt(c.avgCourseContent), fmt(c.avgTeachingQuality),
      fmt(c.avgLabFacilities), fmt(c.avgStudyMaterial), fmt(c.avgOverall),
    ]),
    headStyles: { fillColor: BPUT_BLUE, textColor: 255, fontStyle: "bold", fontSize: 7.5 },
    bodyStyles: { fontSize: 7.5 },
    alternateRowStyles: { fillColor: [245, 249, 255] },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 20 }, 1: { cellWidth: 48 },
      5: { halign: "center" }, 6: { halign: "center" },
      7: { halign: "center" }, 8: { halign: "center" }, 9: { halign: "center", fontStyle: "bold" },
    },
    theme: "grid",
    didDrawCell: (hookData) => {
      if (hookData.section === "body" && hookData.column.index >= 5) {
        const val = parseFloat(hookData.cell.raw as string);
        if (!isNaN(val)) { const col = ratingColor(val); doc.setTextColor(col[0], col[1], col[2]); }
      }
    },
  });

  if (recentComments.length > 0) {
    y = (doc as any).lastAutoTable.finalY + 10;
    if (y > ph - 60) { doc.addPage(); addPageHeader(doc, `${department.code} | Student Comments`); y = 30; }
    y = drawSectionTitle(doc, "E. Student Comments", y);
    autoTable(doc, {
      startY: y,
      margin: { left: M, right: M },
      head: [["Course", "Comment", "Section", "Date"]],
      body: recentComments.map(c => [
        c.courseCode, c.comment ?? "—", c.section ?? "—",
        new Date(c.createdAt).toLocaleDateString("en-IN"),
      ]),
      headStyles: { fillColor: BPUT_BLUE, textColor: 255, fontSize: 8 },
      bodyStyles: { fontSize: 7.5 },
      columnStyles: { 1: { cellWidth: 95 } },
      alternateRowStyles: { fillColor: [245, 249, 255] },
      theme: "grid",
    });
  }

  const pageCount = (doc.internal as any).getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    addPageFooter(doc, i, pageCount);
  }

  doc.save(`CUPGS_${department.code}_Feedback_Report_${new Date().toISOString().slice(0, 10)}.pdf`);
}

type DownloadState = "idle" | "loading" | "done" | "error";

export default function AdminReports() {
  const { role } = useRole();
  const [, navigate] = useLocation();
  const { data: departments } = useListDepartments();

  const [overallState, setOverallState] = useState<DownloadState>("idle");
  const [deptStates, setDeptStates] = useState<Record<number, DownloadState>>({});
  const [fullData, setFullData] = useState<FullReport | null>(null);

  if (role !== "admin") {
    navigate("/");
    return null;
  }

  const downloadOverall = async () => {
    setOverallState("loading");
    try {
      const res = await fetch(`${getApiUrl()}/api/admin/full-report`);
      if (!res.ok) throw new Error("Failed to fetch report data");
      const data: FullReport = await res.json();
      setFullData(data);
      await generateOverallPDF(data);
      setOverallState("done");
      setTimeout(() => setOverallState("idle"), 3000);
    } catch {
      setOverallState("error");
      setTimeout(() => setOverallState("idle"), 3000);
    }
  };

  const downloadDept = async (deptId: number, deptCode: string) => {
    setDeptStates(prev => ({ ...prev, [deptId]: "loading" }));
    try {
      const res = await fetch(`${getApiUrl()}/api/departments/${deptId}/hod-report`);
      if (!res.ok) throw new Error("Failed");
      const data: HodReportData = await res.json();
      await generateDeptPDF(data, true);
      setDeptStates(prev => ({ ...prev, [deptId]: "done" }));
      setTimeout(() => setDeptStates(prev => ({ ...prev, [deptId]: "idle" })), 3000);
    } catch {
      setDeptStates(prev => ({ ...prev, [deptId]: "error" }));
      setTimeout(() => setDeptStates(prev => ({ ...prev, [deptId]: "idle" })), 3000);
    }
  };

  const StateIcon = ({ state }: { state: DownloadState }) => {
    if (state === "loading") return <Loader2 className="w-4 h-4 animate-spin" />;
    if (state === "done") return <CheckCircle className="w-4 h-4 text-green-500" />;
    if (state === "error") return <AlertCircle className="w-4 h-4 text-red-500" />;
    return <Download className="w-4 h-4" />;
  };

  return (
    <div className="p-6 max-w-5xl space-y-8">
      <div className="flex items-start gap-4">
        <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center shrink-0">
          <FileText className="w-6 h-6 text-primary" />
        </div>
        <div>
          <h1 className="text-2xl font-bold">Reports & Downloads</h1>
          <p className="text-muted-foreground text-sm mt-1">
            Download comprehensive PDF reports with charts, tables, ratings, and student comments.
          </p>
        </div>
      </div>

      {/* Overall Institution Report */}
      <div className="bg-gradient-to-br from-blue-950 to-blue-900 text-white rounded-xl p-6 shadow-lg">
        <div className="flex items-start justify-between gap-4 flex-wrap">
          <div className="flex items-start gap-4">
            <div className="w-14 h-14 rounded-xl bg-white/10 flex items-center justify-center shrink-0">
              <BarChart3 className="w-7 h-7 text-blue-200" />
            </div>
            <div>
              <div className="flex items-center gap-2 mb-1">
                <h2 className="text-lg font-bold">Overall Institution Report</h2>
                <Badge className="bg-white/20 text-white hover:bg-white/30 text-xs">PDF</Badge>
              </div>
              <p className="text-blue-200 text-sm">All 7 departments combined — faculty rankings, rating charts, department comparison, student comments</p>
              <div className="mt-2 flex flex-wrap gap-3 text-xs text-blue-300">
                <span className="flex items-center gap-1"><ChevronRight className="w-3 h-3" /> Executive Summary</span>
                <span className="flex items-center gap-1"><ChevronRight className="w-3 h-3" /> Department Comparison Chart</span>
                <span className="flex items-center gap-1"><ChevronRight className="w-3 h-3" /> Rating Breakdown Bars</span>
                <span className="flex items-center gap-1"><ChevronRight className="w-3 h-3" /> Top Faculty Rankings</span>
                <span className="flex items-center gap-1"><ChevronRight className="w-3 h-3" /> Student Comments</span>
              </div>
            </div>
          </div>
          <button
            onClick={downloadOverall}
            disabled={overallState === "loading"}
            className="flex items-center gap-2 bg-white text-blue-900 font-semibold px-5 py-2.5 rounded-lg hover:bg-blue-50 transition-colors disabled:opacity-60 shrink-0 shadow-md"
          >
            <StateIcon state={overallState} />
            {overallState === "loading" ? "Generating…" : overallState === "done" ? "Downloaded!" : overallState === "error" ? "Error — Retry" : "Download Overall Report"}
          </button>
        </div>

        {fullData && (
          <div className="mt-5 grid grid-cols-2 md:grid-cols-5 gap-3">
            {[
              { label: "Total Feedback", val: fullData.overall.totalFeedback },
              { label: "Avg Rating", val: fullData.overall.avgOverall?.toFixed(2) + " / 5" },
              { label: "Departments", val: fullData.overall.totalDepartments },
              { label: "Faculty", val: fullData.overall.totalFaculty },
              { label: "Courses", val: fullData.overall.totalCourses },
            ].map(({ label, val }) => (
              <div key={label} className="bg-white/10 rounded-lg p-3 text-center">
                <div className="text-lg font-bold">{val}</div>
                <div className="text-xs text-blue-300">{label}</div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Per-Department Reports */}
      <div>
        <div className="flex items-center gap-2 mb-4">
          <Building2 className="w-5 h-5 text-primary" />
          <h2 className="text-lg font-semibold">Department-wise Reports</h2>
        </div>
        <p className="text-sm text-muted-foreground mb-5">
          Download a detailed report for each department individually — faculty breakdown, course-wise ratings, and student comments.
        </p>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {departments?.map(dept => {
            const state = deptStates[dept.id] ?? "idle";
            const rating = dept.avgRating;
            const ratingBg = !rating ? "bg-muted" :
              rating >= 4 ? "bg-emerald-100 text-emerald-700" :
              rating >= 3 ? "bg-amber-100 text-amber-700" : "bg-red-100 text-red-700";

            return (
              <div key={dept.id} className="bg-card border rounded-xl p-5 hover:shadow-md transition-shadow">
                <div className="flex items-start justify-between gap-3">
                  <div className="flex items-start gap-3">
                    <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
                      <span className="text-xs font-bold text-primary">{dept.code}</span>
                    </div>
                    <div>
                      <h3 className="font-semibold text-sm leading-tight">{dept.name}</h3>
                      <p className="text-xs text-muted-foreground mt-0.5">
                        {dept.totalFaculty} faculty · {dept.totalCourses} courses
                      </p>
                      <div className="flex items-center gap-2 mt-1.5">
                        <span className={`text-xs font-bold px-2 py-0.5 rounded-full ${ratingBg}`}>
                          {rating ? `★ ${rating.toFixed(2)}` : "No data"}
                        </span>
                        <Badge variant="outline" className="text-xs h-5">PDF</Badge>
                      </div>
                    </div>
                  </div>
                  <Button
                    size="sm"
                    variant={state === "done" ? "outline" : "default"}
                    onClick={() => downloadDept(dept.id, dept.code)}
                    disabled={state === "loading"}
                    className="shrink-0 gap-1.5 text-xs"
                  >
                    <StateIcon state={state} />
                    {state === "loading" ? "Generating…" :
                     state === "done" ? "Downloaded!" :
                     state === "error" ? "Retry" : "Download"}
                  </Button>
                </div>

                <div className="mt-4 grid grid-cols-5 gap-1">
                  {["Content", "Teaching", "Lab", "Material", "Overall"].map(label => (
                    <div key={label} className="text-center">
                      <div className="h-1.5 bg-muted rounded-full overflow-hidden mb-1">
                        <div
                          className={`h-full rounded-full ${
                            !rating ? "bg-muted-foreground/30" :
                            rating >= 4 ? "bg-emerald-500" : rating >= 3 ? "bg-amber-500" : "bg-red-400"
                          }`}
                          style={{ width: rating ? `${(rating / 5) * 100}%` : "0%" }}
                        />
                      </div>
                      <span className="text-xs text-muted-foreground">{label}</span>
                    </div>
                  ))}
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Report legend */}
      <div className="bg-muted/50 border rounded-xl p-5">
        <div className="flex items-center gap-2 mb-3">
          <Shield className="w-4 h-4 text-muted-foreground" />
          <h3 className="text-sm font-semibold text-muted-foreground">Report Legend & Rating Scale</h3>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs text-muted-foreground">
          <div className="space-y-1.5">
            <p className="font-semibold text-foreground mb-1">Rating Colors in PDF</p>
            <div className="flex items-center gap-2"><span className="w-3 h-3 rounded-full bg-green-500 inline-block" /> 4.00–5.00 — Excellent</div>
            <div className="flex items-center gap-2"><span className="w-3 h-3 rounded-full bg-amber-500 inline-block" /> 3.00–3.99 — Satisfactory</div>
            <div className="flex items-center gap-2"><span className="w-3 h-3 rounded-full bg-red-500 inline-block" /> Below 3.00 — Needs Improvement</div>
          </div>
          <div className="space-y-1.5">
            <p className="font-semibold text-foreground mb-1">PDF Sections</p>
            <div>Cover Page with TOC</div>
            <div>Executive Summary with Stats</div>
            <div>Charts (Bar graph, Rating bars)</div>
            <div>Faculty & Course Tables</div>
            <div>Student Comments</div>
          </div>
          <div className="space-y-1.5">
            <p className="font-semibold text-foreground mb-1">Report Details</p>
            <div>Academic Year: 2024-25</div>
            <div>Semester: Even (Sem 6)</div>
            <div>Rating Scale: 1–5</div>
            <div>Classification: Confidential</div>
          </div>
        </div>
      </div>
    </div>
  );
}
